# -*- coding: utf-8 -*-
"""LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wzFstNAezJqhiQbYVeZiywG5vk8sAss4
"""

!pip install --upgrade tensorflow

from google.colab import drive
drive.mount('/content/ColabNotebooks/')

import pandas as pd
import numpy as np

data_path = '/content/ColabNotebooks/MyDrive/ColabNotebooks/FB.csv'
fb_complete_data = pd.read_csv(data_path)
fb_complete_data.head()

fb_training_process = fb_complete_data[['Open']].values

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0,1))
fb_training_scale = scaler.fit_transform(fb_training_process)

len(fb_training_scale)
fb_training_features = []
fb_training_labels =[]

for i in range(60, len(fb_training_scale)):
  fb_training_features.append(fb_training_scale[i-60:i,0])
  fb_training_labels.append(fb_training_scale[i,0])

X_train = np.array(fb_training_features)
y_train = np.array(fb_training_labels)

print(X_train.shape)
print(y_train.shape)

X_train = np.reshape(X_train, (X_train.shape[0], X_train.shape[1],1))

X_train.shape

from re import VERBOSE
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras.layers import Input, Activation , Dense, Flatten, LSTM, Dropout, Flatten
from tensorflow.keras.models import Model

input_layer = Input(shape = (X_train.shape[1],1))
lstm1 = LSTM(100, activation = 'relu' , return_sequences = True) (input_layer)
do1 = Dropout(0.2)(lstm1)
lstm2 = LSTM(100, activation = 'relu' , return_sequences = True) (do1)
do2 = Dropout(0.2)(lstm2)
lstm3 = LSTM(100, activation = 'relu' , return_sequences = True) (do2)
do3 = Dropout(0.2)(lstm3)
lstm4 = LSTM(100, activation = 'relu' ) (do3)
do4 = Dropout(0.2)(lstm4)

output_layer = Dense(1)(do4)
model = Model(input_layer, output_layer)
model.compile(optimizer='adam', loss='mse')

print(X_train.shape)
print(y_train.shape)
y_train = y_train.reshape(-1,1)
print(y_train.shape)

model_history = model.fit(X_train, y_train, epochs=100 , verbose=1, batch_size=32)

test_data_path = '/content/ColabNotebooks/MyDrive/ColabNotebooks/fb_test.csv'
fb_testing_complete_data = pd.read_csv(test_data_path)
fb_testing_processed = fb_testing_complete_data[['Open']].values
fb_all_data = pd.concat((fb_complete_data['Open'], fb_testing_complete_data['Open']), axis=0)
test_inputs = fb_all_data[len(fb_all_data) - len(fb_testing_complete_data) - 60:].values
print(test_inputs.shape)
test_inputs = test_inputs.reshape(-1,1)
test_inputs = scaler.transform(test_inputs)
print(test_inputs.shape)

fb_test_features = []
for i in range(60, len(test_inputs)):
  fb_test_features.append(test_inputs[i-60:i,0])

X_test = np.array(fb_test_features)
print(X_test.shape)
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1],1))
print(X_test.shape)

y_pred = model.predict(X_test)
y_pred = scaler.inverse_transform(y_pred)
plt.figure(figsize=(8,6))
plt.plot(fb_testing_processed, color='red' , label='Actual Facebook Stock Price' )
plt.plot(y_pred , color='green' , label='Predicted Facebook Stock Price' )
plt.title('Facebook Stock Prices' )
plt.xlabel('Date' )
plt.ylabel('Stock Price' )
plt.legend()
plt.show()