# -*- coding: utf-8 -*-
"""ANN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-LOib2_UA6lgs-YUqToioNzA0l3cF7vS
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
# %matplotlib inline
import seaborn as sns
import tensorflow as tf

print(tf.__version__)

from google.colab import drive
drive.mount('/content/ColabNotebooks')

data_path = '/content/ColabNotebooks/MyDrive/ColabNotebooks/train-data.csv'
car_dataset = pd.read_csv(data_path)
car_dataset.head()

car_dataset.isnull().mean()



car_dataset = car_dataset.drop(['Unnamed: 0', 'New_Price'], axis=1)
car_dataset.head()

plt.rcParams['figure.figsize'] = [6,10]
sns.heatmap(car_dataset.select_dtypes(include=np.number).corr(), annot=True)
plt.show()

sns.distplot(car_dataset['Price'])
#plt.show()

car_dataset.nunique()

print(car_dataset.dtypes)

numerical_data = car_dataset.drop(['Name' , 'Location' , 'Fuel_Type' , 'Transmission' , 'Owner_Type' ,
'Mileage' , 'Engine' , 'Power'], axis=1)

numerical_data.head()

categarical_data = car_dataset.filter(['Location' , 'Fuel_Type' , 'Transmission' , 'Owner_Type' , 'Mileage'
 , 'Engine' , 'Power'], axis=1)
categarical_data.head()

categarical_data_one_hot = pd.get_dummies(categarical_data, drop_first=True)
categarical_data_one_hot.head()

complete_dataset = pd.concat([categarical_data_one_hot, numerical_data], axis=1)
complete_dataset.head()

complete_dataset.isnull().mean()

complete_dataset.dropna(inplace=True)

X = complete_dataset.drop(['Price'], axis=1)
y = complete_dataset.filter(['Price'], axis=1)

X_train , X_test, y_train , y_test = train_test_split(X, y, test_size=0.2, random_state=20)

from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

from tensorflow.keras.layers import Input, Dense, Activation, Dropout
from tensorflow.keras.models import Model

input_layer = Input(shape=(X_train.shape[1],))
dense_layer_0 = Dense(100, activation='relu')(input_layer)
dense_layer_1 = Dense(50, activation='relu')(dense_layer_0)
dense_layer_2 = Dense(25, activation='relu')(dense_layer_1)
dense_layer_3 = Dense(10, activation='relu')(dense_layer_2)
dense_layer_4 = Dense(5, activation='relu')(dense_layer_3)
dense_layer_5 = Dense(2, activation='relu')(dense_layer_4)
output = Dense(1)(dense_layer_5)

model = Model(inputs=input_layer, outputs=output)
model.compile(loss="mean_absolute_error" , optimizer="adam" , metrics=["mean_absolute_error"])

from keras.utils import plot_model
plot_model( model, to_file='model_plot.png', show_shapes=True, show_layer_names=True)

history = model.fit(X_train, y_train, batch_size=5, epochs=5, verbose=1, validation_split=0.2)

plt.rcParams['figure.figsize'] = [6,6]
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title('model loss')
plt.ylabel('loss')
plt.xlabel('epoch')
plt.legend(['train', 'test'], loc='upper left')

y_prdeic = model.predict(X_test)

from sklearn import metrics

print('MAE:', metrics.mean_absolute_error(y_test, y_prdeic))
print('MSE:', metrics.mean_squared_error(y_test, y_prdeic))
print('RMSE:', np.sqrt(metrics.mean_squared_error(y_test, y_prdeic)))

car_dataset['Price'].mean()

comparison_df = pd.DataFrame({'Actual Values': y_test.values.tolist(), 'Predicted Values': y_prdeic.tolist()})
comparison_df.head(10)

X_test[1].shape

single_point = X_test[1].reshape(1,-1)
single_point.shape

model.predict(X_test[1].reshape(1,-1))

y_test.values[1 ]

